### ISSUE TITLE
Output Javascript CallBack

### ISSUE THREAD

**Issue by wcjphoenix** [intersystems-ru/webterminal#106]
It would be great to be able to have a Javascript function similar to OnUserInput but OnUserPrompt where the input is all the terminal output from the last user call until the next user prompt.  For example:
w Hi, !, Bye would call OnUserPrompt with the string "Hi /n Bye" or whatever newline character is needed.

If you have any questions or clarifications on what I mean let me know.

Thanks,
Walter Jaskowiak

**Comment by ZitRos** [comment]
Would it sound good to you if I call this API function `onOutput`?

Are you okay with the following API?

`onOutput([options], callback)`
`callback` is `function ( string[] )`
`options` is optional, ` { stream: boolean } `, defaults to false, which means the case you described.

Example, to get the whole output between prompts:

```javascript
terminal.onOutput((outputChunks) => {
    const plainOutputString = outputChunks.join("");
});
```

Note that `outputChunks` is of type `Array` of `string`. Because each output value comes in within different packets, you would also want to check, for example, was it the output from `write 1, 2` or `write 12`. Furthermore, WebTerminal will anyway internally buffer outputChunks into JavaScript array of strings, so, I think, this approach is more universal rather than just returning a string.

Another example, to subscribe for **any** output on the terminal:

```javascript
terminal.onOutput({ stream: true }, (outputChunks) => {
    // each time something comes to the client, this function will be triggered
});
```

**Comment by wcjphoenix** [comment]
That looks fantastic.

**Comment by ZitRos** [comment]
@wcjphoenix, OK! It looks not so hard to implement, I will take this right now.

**Comment by ZitRos** [comment]
@wcjphoenix, by the way, in your project, I think it will make much more sense if `terminal.execute(command, options)` would have optional `callback`, returning output. In this case, you can make a better checks, check the following out.

For example, you want to ensure users sets variable `var` to value `42.15`. How would you do this in terms of `onOutput`? Would you be interested in adding `callback` to `terminal.execute` to be able to do this:

```javascript
terminal.onOutput(() => { // this function runs after user gets a prompt, actually
    // so here you will be able to check if the user did set the variable/whatever to the right value like this:
    terminal.execute("write var", (outputChunks) => {
        const result = outputChunks.join("");
        if (result === "42.15") { // I think we can drop first and last \n newline, as it is constant, maybe.
            alert("Well done, you did the task correctly!");
        } else {
            terminal.print("\r\n\nThat was not your task!\r\n");
        }
    });
});
```

**Comment by ZitRos** [comment]
Hi Walter! I added the discussed functionality to v4.2.1, please test it and close the issue if it satisfies your needs!

And please, respond about the optional callback on `terminal.execute()` - will it be useful for you?

**Comment by wcjphoenix** [comment]
Yeah that would definitely be useful.  I'll grab 4.2.1 and do some testing today.  Thanks for all your help!

**Comment by wcjphoenix** [comment]
Did you mean v4.4.1? I don't see a v4.2.1

**Comment by ZitRos** [comment]
@wcjphoenix, yes, it is 4.4.1, my apologies. Once your test succeeds, please, mark an issue as closed. Let me know if something goes wrong! Thanks!

**Comment by wcjphoenix** [comment]
It works great.  Thanks so much!

**Comment by ZitRos** [comment]
You're welcome! I will create issue requesting for `callback` in terminal.execute soon and let you know.

**Comment by wcjphoenix** [comment]
Awesome, sounds great.
