### ISSUE TITLE
Add installation not in %SYS namespace but with %All mapping

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/webterminal#36]
It prevents from web-terminal deletion after Caché version update.
And it doesn't demand changing read only mode for %CACHELIB

**Comment by eduard93** [comment]
Don't forget to map it into SAMPLES.

**Comment by ZitRos** [comment]
> Don't forget to map it into SAMPLES.

Could you explain this, please?

**Comment by eduard93** [comment]
Not really sure, why would we need installation not in %SYS namespace but with %All mapping at all or if it is even possible.

**Comment by evshvarov** [comment]
%All is not mapped in SAMPLES, that's why we need map to SAMPLES too
manually.

The reason to install not in %SYS is to prevent WT deletion with Cache
version update.

2015-05-24 17:59 GMT+03:00 Eduard <notifications@github.com>:

**Comment by ZitRos** [comment]
@evshvarov and @eduard93, the next step I am going to code in CWT is to "remove" physical CSP/js/css/ico files, and make auto installation of <code>/WebTerminal</code> WEB application during class import, as I just have done in UMLExplorer project.

So I can't really understand why we need to map something to SAMPLES namespace - anyway the application namespace will be %SYS, and it will be accessible from any namespace.

Also I agree with %All mapping, I will try to do it.

**Comment by evshvarov** [comment]
Any news on it?

**Comment by ZitRos** [comment]
Nothing. Spending my time by working on other projects.
But this fix have to come with moving WebTerminal static files to REST classes as well as in Caché Class Explorer.

**Comment by ZitRos** [comment]
OK, Almost done here.

It seems like DOCBOOK namespace needs to be mapped manually as well as SAMPLES.

**Comment by ZitRos** [comment]
Terminal with mapping is almost ready. [Here's the nightly build for testing](https://mega.nz/#!G5M0nRrB!WxZ7gM-o8gARRdlpdh2GwAsNw8sFYeE5sXVG4aU6WFQ).

Everything seem to be good, but I have a strange issue when importing WebTerminal classes first time into studio. It catches an error because of all the WebTerminal's classes are removed from the current namespace you import classes to. The next time you import classes into studio all works good. Why does it happen? My suggestion is that studio tries to open these classes too early when they are in a middle of mapping process and because of that catches the error.

Also, I've noticed that the old version of terminal rises every time I import it's new version! I have to import terminal again, twice, to make updates effective.

Despite of this, mapping has a good pros: no need to mount CACHELIB to not read-only, terminal won't be gone anymore after updating Caché.

**Comment by evshvarov** [comment]
Great news!

пятница, 11 декабря 2015 г. пользователь Nikita написал:

**Comment by eduard93** [comment]
In installer
 set Properties("Database") = "CACHETEMP"

**Comment by ZitRos** [comment]
Works well within version 3.1.4. Mapping and REST migration done. Installer works properly. Closing.
