### ISSUE TITLE
Convert CSP to CLS 

### ISSUE THREAD

**Issue by evshvarov** [intersystems-ru/webterminal#5]
My suggestion is to use webterminal.cls extended from %CSP class.
As the result there will be no phisical CSP file, but all the code in CACHE clasees and js.

**Comment by ZitRos** [comment]
To @evshvarov and other experienced terminal users,

After my [other project](https://github.com/intersystems-ru/UMLExplorer) experienxe I realised that the subject is possible and easy to handle.

Contents of application CSP/JS/CSS files can be moved to CLS XData. By using REST service (one web application) terminal will be ready-to-use always with one URL.

How do you think, is this method of storing files content (I mean XData) is the best one to get rid of CSP/JS/CSS files?

**Comment by tsafin** [comment]
Guys, what is the reason to convert CSP to CLS? What benefits will it provide?
I know only drwbacks - harder editing and debugging. 
[Good luck embedding minified bootstrap css into xdata ]

Don't try to invent Zen once again.

**Comment by ZitRos** [comment]
@tsafin,

> Guys, what is the reason to convert CSP to CLS? What benefits will it provide?

The benefits we see are quite simple - easier and customizable installation for user. Now, installation is a process of importing XML to <b>hardcoded</b> CSP path on the server (to system application csp/sys). There's no usual way to change APP's URL, because even if someone do this, <b>/update</b> will bring it back to <i>csp/sys/webterminal/index.csp</i>, autocomplete won't work because of hardcoded path, etc.

By the idea of transforming CSP/JS/CSS into XData zipped code and adding a few additional code to extract it from user, we are getting one ~%CSP.REST entry point, without any physical files but with one fully-customizable web-application.

Do not worry about

> harder editing and debugging

If you had noticed, code in JS/CSS files is already minified. Usual way to debug the application - run local server and share <code>webSource</code> directory from repository (as I do). By the way, build system (grunt) of project have to be improved, but that's another topic.

> [Good luck embedding minified bootstrap css into xdata ]

Don't understand this. If you had a bad experience, please, share it. Look how things goes [here](https://github.com/intersystems-ru/UMLExplorer/blob/master/cache/projectTemplate.xml#L354). By triggering one command, we have ready-to-install and fully-featured application for Caché in one XML.

Generally, I do work on a project (except Caché classes) <b>outside</b> of Caché studio in my preferred editor, and have only convenient experience on that: <code>change sources, debug, etc. -> build XML from sources by one command -> import & use</code>. Working on big JavaScript/CSS in studio is very awkward, probably you know.

Did I describe the reason well? What is your opinion?

**Comment by eduard93** [comment]
Go for it. {{replace:html}} is an interesting solution. I thought you just filled XDATA automatically from external files on compile (you can write a method, triggered on compile, which would do it).

**Comment by ZitRos** [comment]
1 year and 4 months to become true :)
The issue is finally done due to RESTful'ing terminal application.
