### ISSUE TITLE
Support for system methods in autocomplete

### ISSUE THREAD

**Issue by eduard93** [intersystems-ru/webterminal#57]
2016.1 bought us [system methods](http://localhost:57772/csp/documatic/%25CSP.Documatic.cls?PAGE=CLASS&LIBRARY=%25SYS&CLASSNAME=%25Dictionary.ClassDefinition#PROPERTY_SystemMethods).
For example:
```
set consumedJSON = ##class(%AbstractObject).$fromJSON(someJSONstring)
```

To add support for system methods we need to:
  - on a server side modify `WebTerminal.Autocomplete:GenerateAutocomplete` method
  - on a client side?

Do we add another category for system methods or add them to other methods?

You can check if systems methods are defined via: 
```
w ##class(%Dictionary.PropertyDefinition).IDKEYExists("%Dictionary.ClassDefinition","SystemMethods")
```

Another question - why do we parse `%Dictionary.ClassDefinition` for properties/methods instead of `%Dictionary.CompiledClass`

**Comment by eduard93** [comment]
> Do we add another category for system methods or add them to other methods?

Pros:
  - easier
  - (probaly) no modification of client side is required

Cons:
  - not representative of a class storage
  - may cause problems at a later date

**Comment by ZitRos** [comment]
If the system methods are derived from, for example, %Persistent, then both
the client and a server side has to modified to avoid same data
transmission for over 5000 classes. I'll check this in three days and find
the best solution.

As for compiled class definition it is more correct to use it instead of
class definition.

**Comment by eduard93** [comment]
System methods are another entity altogether:

```
Class %Dictionary.ClassDefinition {

  Relationship Methods As %Dictionary.MethodDefinition [ Cardinality = children, Inverse = parent ];
  Relationship SystemMethods As %Dictionary.SystemMethodDefinition [ Cardinality = children, Inverse = parent ];

}
```

They could be defined anywhere in the system classes, but currently they are defined in 22 classes

| Class |
|----------------------------------------------------|
| %Atelier.Utils.LazyDocument                        |
| %Atelier.Utils.LazyIndex                           |
| %DataModel.DataSource                              |
| %DataModel.Document.Collection                     |
| %DataModel.Document.Database                       |
| %DataModel.Document.Server.Collection              |
| %DataModel.Document.Server.CollectionDescriptor    |
| %DataModel.Document.Server.Database                |
| %DataModel.Document.Server.Index.Iterator.Abstract |
| %DataModel.Document.Server.Index.Iterator.Bitmap   |
| %DataModel.Document.Server.Index.Iterator.KeyMap   |
| %DataModel.Document.Server.Index.Iterator.Map      |
| %DataModel.Document.Server.TemporaryCollection     |
| %DataModel.Document.Type.abstractType              |
| %Iterator.Array                                    |
| %Iterator.Object                                   |
| %Library.AbstractObject                            |
| %Library.Array                                     |
| %Library.Object                                    |
| %Library.RegisteredObject                          |
| %SYSTEM.Document                                   |
| %ZEN.proxyObject                                   |

**Comment by ZitRos** [comment]
So, this won't be so easy to implement: almost all classes are derived from
these. I'll take a closer look on this in days.

**Comment by ZitRos** [comment]
Done with 46789b6a6607b7b7b9ed905f79f6462f713845d3 for ##class constructions.

You were right, Edward, system methods are present only for these classes you've listed above, so it was quite easy to implement.
![2016-03-07_113534](https://cloud.githubusercontent.com/assets/4989256/13565605/ca3a8c4e-e459-11e5-8038-905f2f6ed56e.png)

To be honest, autocomplete mechanism has to be rewritten as CWT does not maintain the following yet:
1. No inline autocomplete: `set cls = ##class(...).%New()` `write cls.<Nothing here>`
2. No private/public method/classmethod classification: `do ##class(...).Method` - incorrect, because `Method` is not ClassMethod;
3. No inherited methods/properties/etc - implementing this over current autocomplete tactics would just overlap browser storage which is limited (5MB for FF, 10 for GC, etc) and also decrease performance;

Once I have a little more time, I will take #58.
