### ISSUE TITLE
Extra information about de user starting the URL

### ISSUE THREAD

**Issue by zenzonx** [intersystems-ru/webterminal#89]
Hello,

Is it possible to get some extra information about de user starting the URL?
I'm searching for a way to get the client-computername and the windows-username.

I was hoping it would be able to get it through the url, like:
http://server:57772/terminal/?TERMID=terminalname&USERID=windowsusername

Any help is appreciated.

**Comment by ZitRos** [comment]
Hello @zenzonx!

I cannot understand your message quite well... Do you need to programmatically take Windows logged username?

Then the possible option is to use WebTerminal's JavaScript API, please refer to [this section](http://intersystems-ru.github.io/webterminal/#docs.4.2.2) in the docs. There is no way for now to have a callback on this function, but you can request for implementing it by creating a separate issue. What this may enable, is, for example, you execute some arbitrary COS command which gets any data from the server, and you would be able to retrieve the output in a callback and process it with JavaScript then.

As for your suggestion, it's not possible to get this data from URL, because URL is formed on a client, and server diesn't care about what data is included in URL. Or I didn't get your question, please, clarify the details (in use-case examples if possible).

Thanks!

**Comment by zenzonx** [comment]
Hi @ZitRos,

Thanks for the quick reply.
First of all, great program.

Second.
I'll leave the username for what it is, because the idea should be the same.

What i'm trying to accomplish is to get the client-computer name (Windows computer name).
When i know WHERE someone logged into, i can set de right printer (or other devices) to this terminal.

I know it can be done through the URL, because someone already made it, but never told me how.
The only thing i found was a (very) small script (CSP) that gave me the right computer name from the URL:

- <script language=cache runat=server>
- set TERMID=$G(%request.Data("TERMID",1))
- </script>

If http://server:57772/terminal/?TERMID=terminalname is the URL, it would give me 'terminalname' as the computer name.
I need a way to transfer 'terminalname' to the WebTerminal session.

Everything else works except this.
It doesn't have to be an URL, but any other good ideas are welcome.

Thanks.

**Comment by ZitRos** [comment]
Thank you! OK, I think I got you.

Try [this](http://intersystems-ru.github.io/webterminal/#docs.2.3.9). You can set the name of the server by using `/config serverName = "terminalname"` in WebTerminal, and then read the ^WebTerminal("Name"), which will contain this value.

Please let me know if this does what you need.

**Comment by ZitRos** [comment]
@zenzonx, please confirm that your question got solved and close this issue if it is. Thank you!

**Comment by zenzonx** [comment]
I'm still working on it, and i think i found a way to do this.
Unfortunately it's more work than i first anticipated.

Thank you for your help so far.
